language: python
sudo: false
branches:
only:
  - master
python:
  - "3.5"
  - "3.6"

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p ./miniconda
  - export PATH=`pwd`/miniconda/bin:$PATH
  - conda update --yes conda
  - conda create -y -q -n test-env python=$TRAVIS_PYTHON_VERSION
  - source activate test-env

install:
  - conda install --yes pip
  - pip install -r requirements_dev.txt

script:
  - python setup.py sdist >/dev/null
  - nosetests --verbose spenc;
notifications:
    email:
        recipients:
            - levi.john.wolf@gmail.com
        on_success: change
        on_failure: always
